# Generated by Django 5.2 on 2025-09-24 07:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_dealerpayout_fulfillment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='custom_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_mode',
            field=models.CharField(choices=[('qikink', 'Qikink Image'), ('custom', 'Custom Image')], default='qikink', max_length=20),
        ),
    ]
