# Generated by Django 5.2 on 2025-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_custom_image_product_image_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
    ]
