# Generated by Django 5.2 on 2025-05-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_productvariant_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
