# Generated by Django 5.2.7 on 2025-10-22 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_banner_mobile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_limit', models.PositiveIntegerField(default=8)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='If set, products will be pulled from this category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
