# Generated by Django 5.2 on 2025-06-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_review_unique_together_review_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
    ]
