# Generated by Django 5.2.7 on 2025-10-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_homesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="Write promo text with emojis and HTML (e.g. 🔥 Get 10% OFF! <a href='/shop'>Shop Now</a>)")),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this banner manually.')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: Show banner starting from this date.', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: Hide banner after this date.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
