# Generated by Django 5.2.7 on 2025-10-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Shown in product list cards', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='special_offer_text',
            field=models.CharField(blank=True, help_text="Optional: e.g. 'Free Shipping', 'Buy 1 Get 4', etc.", max_length=150, null=True),
        ),
    ]
