# Generated by Django 5.2 on 2025-06-11 08:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_client_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
