# Generated by Django 5.2.7 on 2025-10-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_short_description_product_special_offer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
