# Generated by Django 5.2.7 on 2025-11-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='alert_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
