# Generated by Django 5.2.7 on 2025-11-07 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_order_estimated_delivery_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='users',
        ),
        migrations.AddField(
            model_name='coupon',
            name='buy_x',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('GENERIC', 'Generic (anyone can use)'), ('FIRST_ORDER', 'First Order Only'), ('MIN_SPEND', 'Minimum Spend Required'), ('BUY_X_GET_Y', 'Buy X Get Y'), ('USER_SPECIFIC', 'Specific User Only')], default='GENERIC', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='get_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='specific_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
