# Generated by Django 5.2.7 on 2025-11-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_aboutpage_sociallink_value_remove_client_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='button_text',
            field=models.CharField(blank=True, default='Learn More', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, default='Learn More', help_text='Use relative URLs like /shipping/ or /contact/', max_length=200),
            preserve_default=False,
        ),
    ]
