# Generated by Django 5.2.7 on 2025-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_saveditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(choices=[('privacy-policy', 'Privacy Policy'), ('refund-policy', 'Refund & Cancellation Policy'), ('shipping-policy', 'Shipping Policy'), ('terms-conditions', 'Terms & Conditions')], unique=True)),
                ('content', models.TextField(help_text='Use HTML or text')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
