# Generated by Django 5.2.7 on 2025-11-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_sitepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePage',
        ),
    ]
