# Generated by Django 5.2.7 on 2025-11-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_order_shipping_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('home', 'Home'), ('office', 'Office'), ('other', 'Other')], default='shipping', max_length=30),
        ),
    ]
