# Generated by Django 5.2.7 on 2025-12-01 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_coupon_claimed_percent_coupon_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='coupon_image'),
        ),
    ]
