# Generated by Django 5.2.7 on 2025-12-02 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='original_price',
        ),
    ]
