# Generated by Django 5.2.7 on 2026-01-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0044_rename_quantity_productvariant_pack_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveditem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.productvariant'),
        ),
    ]
