# Generated by Django 5.2.7 on 2026-01-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_saveditem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccordionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('default_content', models.TextField(help_text='Plain text only. HTML will be auto-sanitized.')),
                ('schema_key', models.CharField(blank=True, help_text='Schema.org key (e.g. material, shippingDetails)', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAccordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(help_text='Plain text only. HTML not allowed.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('schema_key', models.CharField(blank=True, help_text='Schema.org additionalProperty key', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accordions', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
