# Generated by Django 5.2.7 on 2026-03-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma separated keywords (dress, women dress, party dress)'),
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='store.product')),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='store.product')),
            ],
            options={
                'unique_together': {('product', 'related_product')},
            },
        ),
    ]
