# Generated by Django 5.2.7 on 2026-03-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_searchquery_product_keywords_productrelation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='store_produ_name_5e57da_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['keywords'], name='store_produ_keyword_1669a0_idx'),
        ),
    ]
