# Generated by Django 5.2.7 on 2026-04-09 05:38

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_product_store_produ_name_5e57da_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='store.brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['parent'], name='store_brand_parent__6096d8_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['tree_id', 'lft'], name='store_brand_tree_id_lft_idx'),
        ),
    ]
