# Generated by Django 5.2.7 on 2026-04-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_brand_level_brand_lft_brand_parent_brand_rght_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price — must be less than MRP', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Original MRP — must be greater than 0', max_digits=10),
        ),
    ]
