# Generated by Django 5.2.7 on 2026-04-24 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_order_cancelled_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='aftership_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fulfillment',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TrackingCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('checkpoint_time', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='store.order')),
            ],
            options={
                'ordering': ['-checkpoint_time'],
            },
        ),
    ]
