# Generated by Django 5.2.7 on 2026-04-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_fulfillment_aftership_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_default_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='use_as_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='use_as_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
