# Generated by Django 5.2.7 on 2026-04-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_address_is_default_billing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
