from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import CustomPasswordChangeView, account_dashboard, update_avatar, CombinedLoginView, CustomSignupView

urlpatterns = [
    path('', views.index, name='index'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path("cart/", views.cart_view, name="cart"),
    path("cart/add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("cart/update/<int:item_id>/", views.update_cart, name="update_cart"),
    path("cart/remove/<int:item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("cart/save/<int:item_id>/", views.save_for_later, name="save_for_later"),
    path("cart/move/<int:product_id>/", views.move_to_cart, name="move_to_cart"),
    path("order-success/", views.order_success, name="order_success"),
    path('products/', views.products_view, name='products'),
    path("about/", views.about, name="about"),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('contact/', views.contact_view, name='contact'),
    path('contact_thanks/', views.contact_thanks, name='contact_thanks'),
    path('search_results/', views.search_view, name='search_results'),
    path("search-suggestions/", views.search_suggestions, name="search_suggestions"),
    path('wishlist/', views.wishlist_view, name='wishlist'),
    path('toggle-price-alert/<int:product_id>/', views.toggle_price_alert, name='toggle_price_alert'),
    path('notify-me/<int:product_id>/', views.notify_me_stock, name='notify_me_stock'),
    path('add_to_wishlist/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),
    path('otp-login/', views.send_email_otp, name='otp_login'),
    path('verify-email-otp/', views.verify_email_otp, name='verify_email_otp'),
    path('otp-success/', views.otp_success, name='otp_success'),
    path('account/dashboard/', views.account_dashboard, name='account_dashboard'),
    path("account/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("account/settings/", views.account_settings, name="account_settings"),
    path("account/addresses/", views.addresses, name="account_addresses"),
    path("account/addresses/<int:pk>/set-default/", views.set_default_address, name="set_default_address"),
    path("account/addresses/add/", views.address_add, name="address_add"),
    path("account/addresses/<int:pk>/edit/", views.edit_address, name="edit_address"),
    path("account/addresses/<int:pk>/delete/confirm/", views.address_delete_confirm, name="address_delete_confirm"),
    path("account/addresses/<int:pk>/delete/", views.delete_address, name="delete_address"),
    path("account/password/change/", CustomPasswordChangeView.as_view(), name="account_change_password"),
    path("accounts/login/", CombinedLoginView.as_view(), name="account_login"),
    path("accounts/signup/", CustomSignupView.as_view(), name="account_signup"),
    path("payments/", views.payments, name="payments"),
    path("offers/", views.account_offers, name="offers"),
    path("checkout/", views.checkout, name="checkout"),
    path("cart/apply-coupon/", views.apply_coupon_ajax, name="apply_coupon_ajax"),
    path("create-discounted-order/", views.create_discounted_order_ajax, name="create_discounted_order_ajax"),
    path("payment/success/", views.payment_success, name="payment_success"),
    path("orders/", views.orders_list, name="orders"),
    path("orders/<int:order_id>/", views.order_detail, name="order_detail"),
    path("orders/<int:order_id>/track/", views.track_order, name="track_order"),
    path("orders/<int:order_id>/return/", views.request_return, name="request_return"),
    path("returns/<int:return_id>/", views.return_detail, name="return_detail"),
    path("orders/<int:order_id>/invoice/", views.download_invoice, name="download_invoice"),
    path('category/<slug:slug>/', views.category_products, name='category_products'),
    path('fetch-products/', views.fetch_products, name='fetch_products'),
    path("account/upload-avatar/", update_avatar, name="account_upload_avatar"),
    path('faq/', views.faq_view, name='faq'),
    path("subscribe/", views.subscribe_newsletter, name="subscribe_newsletter"),
    path("offer/<int:coupon_id>/grab/", views.grab_offer, name="grab_offer"),
    path("remove-coupon/", views.remove_coupon, name="remove_coupon"),
    path('receipt/<int:payment_id>/', views.download_receipt, name='download_receipt'),
]
