# Generated by Django 5.2.7 on 2025-11-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
